### ISSUE TITLE
Explore different namespaces and view key detail

### ISSUE THREAD

**Issue by gdavalos** [streamrail/dsui#3]
Hi there, I'm trying to use dsui with the datastore emulator and it's pretty neat, I've just got a couple of things I want to do that I'm not sure if dsui can do them yet.

The first is viewing anything that's not in the default namespace and the second is viewing the detail for the key's path value.

Is there anyway to do those? Do you plan to implement them?

**Comment by ramybenaroya** [comment]
Hi, I just released [v.0.1.0](https://github.com/streamrail/dsui/releases/tag/v0.1.0) with:
- Query by Namespace
- Show Path & Namespace in Key column and as the header of the entity view screen.

**Comment by gdavalos** [comment]
How can I install it though? npm just gives me a not found error

**Comment by gdavalos** [comment]
There's a bit of a problem in my case, my non-default namespaces have Entities of types which don't exist in the default namespace and I can't see them with dsui v.0.1.0

**Comment by ramybenaroya** [comment]
You are right. I will reopen and add a fix

**Comment by ramybenaroya** [comment]
Fixed in [v0.1.1](https://github.com/streamrail/dsui/releases/tag/v0.1.1)

**Comment by qushot** [comment]
The namespace problem does not seem to be solved with dsui v0.2.2.
I can't see Entities from non-default namespaces.

**Comment by QuantumInformation** [comment]
Yep issue still exists with latest npm version

**Comment by QuantumInformation** [comment]
I can't even see any data with the default namespace
