### ISSUE TITLE
If names are longer than expected, data overlaps

### ISSUE THREAD

**Issue by brunoais** [streamrail/dsui#4]
If names are long (anonymized in the image shown), the row's data overlaps
![image](https://user-images.githubusercontent.com/639467/39879351-80517cb0-5472-11e8-8b5b-a35ae764ef91.png)
To solve this, I suggest removing the `nowrap` from the `style.css`
I rather have it span over multiple lines than having it overlapping like this.

**Comment by ramybenaroya** [comment]
Fixed in [v0.1.2](https://github.com/streamrail/dsui/releases/tag/v0.1.2)
